//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class question
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public question()
    {
        this.solved_by = new HashSet<solved_by>();
    }

    public int question_id { get; set; }
    public Nullable<int> question_by { get; set; }
    public string question_include { get; set; }
    public string answer { get; set; }
    public string title { get; set; }

    public virtual user user { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<solved_by> solved_by { get; set; }
}

public partial class solved_by
{
    public int solved_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> question_id { get; set; }

    public virtual question question { get; set; }
    public virtual user user { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class user
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {
        this.question = new HashSet<question>();
        this.solved_by = new HashSet<solved_by>();
    }

    public int id { get; set; }
    public string firstname { get; set; }
    public string surname { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public Nullable<int> puan { get; set; }
    public Nullable<int> is_reviewer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<question> question { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<solved_by> solved_by { get; set; }
}
